module.exports = {
    PLACES_TO_BE_COLLECTED: 'PLACES_TO_BE_COLLECTED',
    SYNC_EXECUTE: 'SYNC_EXECUTE',
    CYCLE_GROUP_MOVEMENTS: 'CYCLE_GROUP_MOVEMENTS',
    CREATE_MOVEMENT: 'CREATE_MOVEMENT',
    CYCLE_OPTIONS: 'CYCLE_OPTIONS',
    RUN_CYCLE_GROUP_MOVEMENTS: 'RUN_CYCLE_GROUP_MOVEMENTS',
    RUN_REQUEST: 'RUN_REQUEST'
}